### ISSUE TITLE
Transparent Background?

### ISSUE THREAD

**Issue by aronduby** [rohanliston/adobe-spritesheet-scripts#2]
This is so much nicer!!! Thank you!

Is there a way to get it to render transparent? Right now I run the script (after making that pull request) and it renders the composition background but I need transparency. If you can just point me in the right direction I'll try to do it as an option and do another PR.

I'm using AE CS6 and PS CS5 on Windows.

**Comment by rohanliston** [comment]
@aronduby Sorry, I hadn't enabled notifications for this repository and only noticed your pull request/issue today.

I had a play around with this a while back. It seems that the transparency does in fact export properly from After Effects, but is lost when copying the frames over into the one image in Photoshop. The Alpha channel isn't copied over for some reason.

Currently, the workaround is to use Photoshop's built-in _Load Files Into Stack..._ script, then run my _Sprite Sheet from Photoshop Layers_ script to generate the sheet. Not as automated, but it works.

In general, the spritesheet script is getting pretty crusty (written in 2011 for CS4), and wasn't particularly well-written in the first place. There are a surprising number of people using these scripts, so it would be worth my while rewriting them altogether. I have started on a version that does the whole thing from After Effects, skipping Photoshop altogether.

**Comment by rohanliston** [comment]
@aronduby I've completely rewritten the `after_effects_spritesheet_exporter` script from scratch; it's a lot tidier, about 100 times faster, doesn't involve Photoshop, and works on Adobe CC 2015 (for OSX at least). I'll move onto the other scripts shortly.

The transparency issue should now be addressed. Currently, the script exports PSD files containing an alpha channel, which can then be saved to a format with baked alphas such as PNG.

I'd love to be able to render PNGs right off the bat, as that's what I usually use, but After Effects' render template system is complete garbage and doesn't give me any way to set one up programmatically. To address this, I'm planning on exporting PSDs by default and letting the user specify the name of an alternative render template that they create themselves.
