### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sid9000** [rohanliston/adobe-spritesheet-scripts#4]
After Effects CC 2015. Win 10.

Upon running script I get this error.  "Unable to execute script at line 40. sheetifyDialogContents is undefined."

**Comment by thealexus** [comment]
File SheetifyDialog.jsx, line 40:
replace 
`this.contents = sheetifyDialogContents;`
with
`this.contents = SheetifyDialogContents;`

**Comment by rohanliston** [comment]
Closing as duplicate of https://github.com/rohanliston/adobe-spritesheet-scripts/issues/3
